name = "backend"
compatibility_date = "2024-08-19"

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWM0MjY4ZDEtNGNjNi00MGNiLTg2OTQtYzkyM2JmODM2OGY0IiwidGVuYW50X2lkIjoiYjZkNGJkNDFlNGQ5N2VjZDVkYmMzNzk4MzRmNDk4MDQwZmZlZDA3ZDlhMjkxNmFlMzA3YjczMzU1ZDllM2JiYyIsImludGVybmFsX3NlY3JldCI6IjU5M2M5YmNkLTFmMDUtNDk4OS1hODA2LTY5MDQ1ODk3NzEyMiJ9.xLra6kGXU1Q2-XLpHY-ga_rJNnh2s1nvigB2cRxo-Sc" 
JWT_SECRET="deepak"
